"""
Detection Signal 1: LLM-based structured assessment.

Sends the submitted text to an LLM (Groq's OpenAI-compatible chat completions
API) with a prompt asking it to return a structured JSON assessment of how
likely the text is to be AI-generated. This is "Signal 1" from planning.md.

Falls back to a deterministic, offline heuristic scorer when no GROQ_API_KEY
is configured, or if the API call fails for any reason (network, rate limit,
bad response). The fallback exists purely so the app is runnable and testable
without credentials or network access — it is NOT a substitute for the real
signal and is clearly labeled as such in its output (`source` field).
"""

import os
import re
import json

import requests

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.1-8b-instant")

SYSTEM_PROMPT = (
    "You are a text-provenance analyst. Given a piece of text, assess how "
    "likely it is to have been generated by an AI language model versus "
    "written by a human. Consider word predictability, phrasing patterns, "
    "cliche transitions, and stylistic tells. Respond with ONLY a JSON "
    'object of the form: {"llm_score": <float 0.0-1.0>, "reasoning": '
    '"<one short sentence>"} where 1.0 means certainly AI-generated and 0.0 '
    "means certainly human-written. Do not include any text outside the "
    "JSON object."
)


def _call_groq(text: str) -> dict:
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY not set")

    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text[:6000]},  # guard against huge payloads
        ],
        "temperature": 0,
        "max_tokens": 150,
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    resp = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=15)
    resp.raise_for_status()
    content = resp.json()["choices"][0]["message"]["content"]
    parsed = json.loads(content)
    score = float(parsed["llm_score"])
    return {
        "llm_score": max(0.0, min(1.0, score)),
        "reasoning": parsed.get("reasoning", ""),
        "source": "groq",
    }


# --- Offline fallback -------------------------------------------------

_COMMON_WORDS = {
    "the", "a", "an", "and", "or", "but", "of", "to", "in", "on", "for",
    "with", "as", "is", "was", "are", "were", "be", "been", "it", "this",
    "that", "these", "those", "at", "by", "from", "into", "over", "after",
    "before", "which", "who", "what", "when", "where", "how", "why", "not",
    "no", "so", "if", "then", "than", "such", "also", "however",
}

_TRANSITION_PATTERN = re.compile(
    r"\b(moreover|furthermore|additionally|overall|in conclusion|in summary|"
    r"it is important to note|it'?s worth noting|in today's|on the other hand|"
    r"plays a (crucial|vital|significant|key) role|underscores?|delve into|"
    r"navigate the|the landscape of|in the realm of|leverage|harness the|"
    r"paradigm shift|at the end of the day|when it comes to)\b",
    re.IGNORECASE,
)


def _heuristic_score(text: str) -> dict:
    """
    Offline proxy for "predictability": leans on common connective words,
    formulaic AI-essay phrasing, and lexical diversity as a rough stand-in
    for the real LLM assessment. Only used when Groq is unavailable, so
    local dev/grading isn't blocked on an API key.

    Debugging against the milestone's test set showed unique-word-ratio is
    the same weak, short-text-biased metric that TTR turned out to be in
    signal_2_stylometric.py - short paragraphs are lexically diverse almost
    regardless of origin. It's kept as a minor factor, not a primary one;
    formulaic-phrase density carries most of the weight instead.
    """
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if not words:
        return {"llm_score": 0.5, "reasoning": "empty text", "source": "heuristic_fallback"}

    common_ratio = sum(1 for w in words if w in _COMMON_WORDS) / len(words)
    unique_ratio = len(set(words)) / len(words)
    transition_hits = len(_TRANSITION_PATTERN.findall(text))
    transition_density = min(transition_hits / 3, 1.0)  # 3+ hits maxes this out

    raw = (0.25 * common_ratio) + (0.15 * (1 - unique_ratio)) + (0.60 * transition_density)
    score = max(0.0, min(1.0, raw))
    return {
        "llm_score": round(score, 3),
        "reasoning": "offline heuristic fallback (no GROQ_API_KEY set)",
        "source": "heuristic_fallback",
    }


def signal_1_score(text: str) -> dict:
    """
    Returns {"llm_score": float, "reasoning": str, "source": str}.
    Tries the real Groq-backed signal first; falls back to a local
    heuristic on any failure so the endpoint never hard-fails on signal 1.
    """
    try:
        return _call_groq(text)
    except Exception:
        return _heuristic_score(text)
